sudo: required
language: python

# Specify the version of python
python:
  - "3.5"

# Specify branchs that travis will monitor
branches:
  only:
    - master

# Use docker to deploy
service:
  - docker

# Specify the docker-compose version to deploy
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

# Install project dependencies
install:
  - docker-compose up -d

# Run the tests and create coverage.xml
script:
  - docker exec tbl python manage.py test **/tests/
