version: '3'
services:
  tbl-local:
    image: victorhad/tbl:local
    container_name: tbl-local
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    volumes:
      - .:/home/developer/software
    ports:
      - "8000:8000"
